# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/Lms.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/Lms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/Lms.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"l\n\x1bUploadCourseMaterialRequest\x12\x0e\n\x06\x63ourse\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x0f\n\x07\x63reated\x18\x05 \x01(\t\"I\n\x1cUploadCourseMaterialResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\";\n\rLoginResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t2h\n\x04\x41uth\x12/\n\x0cstudentLogin\x12\r.LoginRequest\x1a\x0e.LoginResponse\"\x00\x12/\n\x0c\x66\x61\x63ultyLogin\x12\r.LoginRequest\x1a\x0e.LoginResponse\"\x00\x32\x64\n\tMaterials\x12W\n\x14\x63ourseMaterialUpload\x12\x1c.UploadCourseMaterialRequest\x1a\x1d.UploadCourseMaterialResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.Lms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=20
  _globals['_LOGINREQUEST']._serialized_end=70
  _globals['_UPLOADCOURSEMATERIALREQUEST']._serialized_start=72
  _globals['_UPLOADCOURSEMATERIALREQUEST']._serialized_end=180
  _globals['_UPLOADCOURSEMATERIALRESPONSE']._serialized_start=182
  _globals['_UPLOADCOURSEMATERIALRESPONSE']._serialized_end=255
  _globals['_LOGINRESPONSE']._serialized_start=257
  _globals['_LOGINRESPONSE']._serialized_end=316
  _globals['_AUTH']._serialized_start=318
  _globals['_AUTH']._serialized_end=422
  _globals['_MATERIALS']._serialized_start=424
  _globals['_MATERIALS']._serialized_end=524
# @@protoc_insertion_point(module_scope)
